services:
  django:
    build: ./back_generador_bd/
    container_name: django_backend_UML
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=uml_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=071104
      - CORS_ALLOWED_ORIGINS=http://localhost:4000,http://angular-app:4000
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 diagramador_uml.asgi:application"

    volumes:
      - ./back_generador_bd:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./back_generador_bd/.env
    networks:
      - backend  
      - frontend

  redis:
    image: public.ecr.aws/docker/library/redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - backend

  spring-backend:
    build: ./back_generator_uml/
    container_name: spring_backend
    environment:
      - SERVER_PORT=7000
    ports:
      - "7000:7000"

    depends_on:
      - angular-app
    networks:
      - backend
      - frontend

  angular-app:
    build: ./front_generador_bd/
    container_name: angular_frontend
    ports:
      - "4000:4000"
    networks:
      - frontend
      - backend

networks:
  backend:
    external: true
  frontend:
    driver: bridge